from enum import Enum


class Tile(Enum):
    GHOST_HOUSE = -3
    GHOST_START = -2
    PLAYER_START = -1
    WALL_OUTER_TOP_LEFT_CORNER = 0
    WALL_LEFT = 1
    WALL_OUTER_BOTTOM_LEFT_CORNER = 2
    WALL_DOUBLE_TOP_LEFT_CORNER = 3
    WALL_DOUBLE_LEFT = 4
    WALL_DOUBLE_BOTTOM_LEFT_CORNER = 5
    WALL_TOP = 6
    AIR = 7
    WALL_BOTTOM = 8
    WALL_DOUBLE_TOP = 9
    GHOST_GATE = 10
    WALL_DOUBLE_BOTTOM = 11
    WALL_OUTER_TOP_RIGHT_CORNER = 12
    WALL_RIGHT = 13
    WALL_OUTER_BOTTOM_RIGHT_CORNER = 14
    WALL_DOUBLE_TOP_RIGHT_CORNER = 15
    WALL_DOUBLE_RIGHT = 16
    WALL_DOUBLE_BOTTOM_RIGHT_CORNER = 17
    WALL_INNER_BOTTOM_RIGHT_CORNER = 18
    WALL_INNER_TOP_RIGHT_CORNER = 19
    SMALL_DOT = 20
    WALL_SQUARE_DOUBLE_TOP_LEFT_CORNER = 21
    WALL_SQUARE_DOUBLE_BOTTOM_LEFT_CORNER = 22
    WALL_SQUARE_DOUBLE_TOP_RIGHT_END = 23
    WALL_INNER_BOTTOM_LEFT_CORNER = 24
    WALL_INNER_TOP_LEFT_CORNER = 25
    BIG_DOT = 26
    WALL_SQUARE_DOUBLE_TOP_RIGHT_CORNER = 27
    WALL_SQUARE_DOUBLE_BOTTOM_RIGHT_CORNER = 28
    WALL_SQUARE_DOUBLE_TOP_LEFT_END = 29
    WALL_JUNCTION_TOP_LEFT = 30
    WALL_JUNCTION_TOP_RIGHT = 31
    WALL_JUNCTION_LEFT_TOP = 32
    WALL_JUNCTION_LEFT_BOTTOM = 33
    WALL_JUNCTION_RIGHT_TOP = 34
    WALL_JUNCTION_RIGHT_BOTTOM = 35
